name: academic
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.3
  chat_gpt_sdk:
    git:
      url: https://github.com/iampawan/Flutter-ChatGPT.git
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^15.1.0+1
  flutter_native_splash: ^2.2.19
  get: ^4.6.5
  google_fonts: ^4.0.3
  google_sign_in: ^6.0.2
  googleapis: ^10.1.0
  http: ^0.13.5
  package_info_plus: ^4.0.2
  riverpod: ^2.5.0
  smooth_page_indicator: ^1.0.1
  speech_to_text: ^6.6.0
  table_calendar: ^3.0.1
  markdown_viewer: ^0.6.2
  sqflite: ^2.3.2
  flutter_tex: ^4.0.6
  flip_card: ^0.7.0
  pie_chart: ^5.4.0
  provider: ^6.1.2
  intl: ^0.18.1
  uuid: ^4.3.3

  chewie: ^1.7.5
  video_player: ^2.8.5
  appinio_video_player: ^1.2.2
  flutter_riverpod: ^2.5.1
  infinite_scroll_pagination: ^4.0.0
  hive: ^2.2.3
  csv: ^5.0.2
  external_path: ^1.0.3
  device_info_plus: ^9.0.1
  modal_bottom_sheet: 3.0.0-pre
  flutter_native_timezone_updated_gradle: ^2.0.3
  timezone: ^0.9.2
  hive_flutter: ^1.1.0
  permission_handler: ^10.4.3
  launch_review: ^3.0.1
  url_launcher: ^6.2.5
  path_provider: ^2.0.15
  syncfusion_flutter_calendar: ^21.2.6
  syncfusion_flutter_core: ^21.2.10
  hive_generator: ^2.0.1


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/mood/
    - assets/images/icon/
    - .env

flutter_native_splash:
  background_image: assets/images/splash.png
  color: "#F0E8D5"
  android: true
  ios: true
